from . import hr_employee
from . import employee_trip
from . import employee_education
from . import employee_certificate
from . import hr_employee_work_process_tedi
from . import hr_employee_work_process_old
from . import hr_employee_experience
from . import hr_employee_reward_discipline
from . import hr_party_cell
from . import hr_party_title
from . import hr_employee_training