[options]
addons_path = /opt/odoo17_tedi/addons_t,/opt/odoo17_tedi/addons_c
admin_passwd = 123456t@
bin_path = /usr/local/bin/wkhtmltopdf
data_dir = /opt/odoo17_tedi/filedata
db_host = localhost
db_maxconn = 64
db_name = False
db_password = Tedi@2025
db_port = 5432
db_sslmode = prefer
db_template = template0
db_user = odoo17_tedi
dbfilter = ^tedi  
demo = {}
xmlrpc = True
xmlrpc_interface = 0.0.0.0
xmlrpc_port = 8069
limit_time_cpu = 12000
limit_time_real = 240000
log_level=info
gevent_port = 8072
workers = 6
default_productivity_apps = True
list_db = True
logfile = /opt/odoo17_tedi/odoo.log
max_cron_threads = 4
osv_memory_age_limit = False
osv_memory_count_limit = 0
pg_path = /usr/lib/postgresql/12/bin
proxy_mode = True
server_wide_modules = base,web
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
websocket_keep_alive_timeout = 120
websocket_rate_limit_burst = 10
websocket_rate_limit_delay = 0.2
force_secure = True
