[options]
admin_passwd = $pbkdf2-sha512$600000$zdmbc.7d25uz9r4XYmztPQ$udTHlO42WiFsHz4rhgfgEXNfhIU9aHwmPPH.0BQCM.xMip7ulaCPo9uI8nrPnPI/xi7y6lmtFRkOxdjYxpn./Q

bin_path = C:/Program Files/wkhtmltopdf/bin