{
    'name': "TEDI: Dự án",
    'version': "1.0",
    'summary': "",
    'description': """""",
    'category': 'TEDI/Project',
    'author': "YourCompany",
    'depends': ['project', 'account', 'web'],
    'data': [
        'security/ir.model.access.csv',
        # 'views/asset_inherit.xml',
        'datas/default_data.xml',
        'views/project.xml',
        'views/task.xml',
        'wizard/task_progress_wizard.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # '/project_tedi/static/src/css/tree_view_style.css',
            # '/style_custom/static/src/css/custom_dynamic_styles.css',
            # '/style_custom/static/src/css/custom_font_size.css',
            # '/style_custom/static/src/js/load_dynamic_css.js',
            # '/style_custom/static/src/js/load_font_size.js',
            # '/style_custom/static/src/js/load_login_bg.js',
            # '/style_custom/static/src/css/notebook_custom.css',
            # '/style_custom/static/src/css/breadcrumb_color.css',
            # '/style_custom/static/src/css/save_cancel_button.css',
            # '/style_custom/static/src/js/load_user_name.js',
            # '/style_custom/static/src/css/hidden_button.css',
            # '/style_custom/static/src/css/search_custom.css',
        ],
        # 'web.assets_frontend': [
        #     '/style_custom/static/src/css/login_custom.css',
        # ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
